import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";


const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "FitLog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col ${oswald.className}`}>{children}</body>
    </html>
  );
}
